services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DVC\AsyncPagination\Controller\ContentElement\AsyncPaginationWrapperController:

  DVC\AsyncPagination\EventListener\AddFrontendScriptToContentElementListener:
